version: '3'
services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: urban_complaint_development
    ports:
      - "5432:5432"

  web:
    build: 
      context: ..
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/rails:cached
      - /rails/tmp
      - /rails/log
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/urban_complaint_development
      RAILS_ENV: development
      SECRET_KEY_BASE: development_key

volumes:
  postgres_data:
